# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addy', '0002_companyapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_student',
            name='student_roll',
            field=models.IntegerField(),
        ),
    ]
