# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addy', '0003_auto_20160526_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='author',
            new_name='subject',
        ),
    ]
