# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addy', '0004_auto_20160527_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_openings',
            name='eligiblity',
        ),
        migrations.AddField(
            model_name='job_openings',
            name='eligible_departments',
            field=models.ManyToManyField(to='addy.Department'),
        ),
    ]
