# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addy', '0005_auto_20160527_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_openings',
            name='eligiblity',
            field=models.CharField(default='none', max_length=1024),
        ),
    ]
